name: APE Java CI

on:
  push:
    paths:
      - 'oap-ape/**'
      - '.github/**'
  pull_request:
    paths:
      - 'oap-ape/**'
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: oap-common dependency
        run: git clone https://github.com/Intel-bigdata/OAP.git; cd OAP; git checkout v0.9.0-spark-3.0.0; mvn install -pl oap-common -am;
      - name: Build with Maven
        run: cd oap-ape/ape-java; mvn clean package -am